version: '3.8'

services:
  # Go application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=aboba
      - DB_PASSWORD=12345
      - DB_NAME=Books
    volumes:
      - .:/BooksAPI  # Mount the local directory to the container
    networks:
      - app_network

  # PostgreSQL service
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: aboba
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Books
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local

